name: Build Android APK

on:
  push:
    branches: [ v8-final ]
  pull_request:
    branches: [ v8-final ]
  workflow_dispatch:  # يسمح أيضًا بالتشغيل اليدوي

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Static analysis
        run: flutter analyze

      - name: Build APKs
        run: flutter build apk --release --split-per-abi

      - name: Upload ARM64 APK
        uses: actions/upload-artifact@v4
        with:
          name: Ihsaa-v8-ARM64
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      - name: Upload ARMv7 APK
        uses: actions/upload-artifact@v4
        with:
          name: Ihsaa-v8-ARMv7
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

      - name: Upload Universal APK
        uses: actions/upload-artifact@v4
        with:
          name: Ihsaa-v8-Universal
          path: build/app/outputs/flutter-apk/app-release.apk
